from aiogram.dispatcher.filters.state import StatesGroup, State


class BuyoutMenuState(StatesGroup):
    start = State()
    my_buyouts = State()
    templates = State()
    make_templates = State()
    make_templates_link = State()
    make_templates_keywords = State()
    make_templates_address = State()
    make_templates_address_confirm = State()
    make_templates_confirm = State()
    my_template_make_buyout = State()
    my_template_make_buyout_male = State()
    my_template_make_buyout_confirm = State()
    #make_buyout = State()
    make_buyout_link = State()
    make_buyout_keywords = State()
    make_buyout_count = State()
    make_buyout_address = State()
    make_buyout_address_confirm = State()
    make_buyout_male = State()
    make_buyout_confirm = State()
    make_buyout_after_payment = State()
    timetable_buyouts = State()
    timetable_buyouts_dates = State()
    timetable_buyouts_time = State()
    timetable_buyouts_dates_choice_template = State()
    timetable_buyouts_count = State()
    timetable_buyouts_male = State()
    timetable_buyouts_dates_confirm = State()
    timetable_buyouts_dates_payment = State()
    timetable_buyouts_dates_payment_check = State()
    my_buyouts_get_code = State()
    my_buyouts_get_code_confirm = State()
    end = State()
